package vista;

import javax.swing.*;
import controlador.GameControl;
import java.awt.Color;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.Scanner;
import javax.imageio.ImageIO;
import modelo.jugador.Record;

public class MenuPanel extends javax.swing.JPanel {

    /**
     * el panel menu
     * se crean los componentes con la herramienta de netbeans
     * luego se posicionan con el metodo posicionar
     */
    private GameControl gm;
    
    public MenuPanel(GameControl gm) {
        this.gm = gm;
        setSize(gm.getPanel().getSize());
        initComponents();        
        posicionarComponents();        
        repaint();
    }
    
    private void posicionarComponents(){
        int y = 5*getHeight()/7;
        int x = (getWidth()/2)-(nuevoJuegoButton.getWidth()/2);
        nuevoJuegoButton.setLocation(x,y);
        
        y+= nuevoJuegoButton.getHeight() + 10;                       
        x = (getWidth()/2)-(salirButton.getWidth()/2);
        salirButton.setLocation(x,y);
                
        try{
            Image img = ImageIO.read(getClass().getResource("/images/menu_background.jpeg"));
            img = img.getScaledInstance(getWidth(),getHeight(),Image.SCALE_SMOOTH);
            
            fondo.setIcon(new ImageIcon(img));
            fondo.setSize(getSize());
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        
    }           

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoJuegoButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(null);

        nuevoJuegoButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nuevoJuegoButton.setText("NUEVO JUEGO");
        nuevoJuegoButton.setFocusable(false);
        nuevoJuegoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoJuegoButtonActionPerformed(evt);
            }
        });
        add(nuevoJuegoButton);
        nuevoJuegoButton.setBounds(90, 110, 220, 65);

        salirButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        salirButton.setText("SALIR");
        salirButton.setFocusable(false);
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        add(salirButton);
        salirButton.setBounds(90, 220, 220, 65);
        add(fondo);
        fondo.setBounds(0, 0, 0, 0);
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed

    private void nuevoJuegoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoJuegoButtonActionPerformed
        (new Thread(){
            public void run(){
                gm.startGame();
            }
        }).start();
    }//GEN-LAST:event_nuevoJuegoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton nuevoJuegoButton;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
